apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      # version: ">=7.1.0"
  interval: 30m0s
  # values:
  #   logging:
  #     enabled: true


# helm install traefik traefik/traefik --set