apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: wordpress
        namespace: default
  interval: 30m0s
  values:
    wordpressUsername: admin
    wordpressPassword: 1234